import React from "react";
import {StyleSheet, Text, TouchableOpacity, View} from "react-native";
import { commonStyles, colors } from "./common";
import QRCodeScanner from 'react-native-qrcode-scanner';
import { setPairing } from "../utils";

class PairingScreen extends React.Component {

    temp() {
        setPairing("Sasha's PC", 'true')
        this.props.navigation.state.params.refreshFunction();
        this.props.navigation.navigate('Home');
    };

    pairDevice(value) {
      split = value.split('|');
      alert(split);
      key = split[0];
      iv = split[1];
      pcName = split[2];
      setPairing(key, iv, pcName, 'true');
    }

    render() {
        return (
            <View style={{alignItems: "center"}}>
                <Text  style={commonStyles.instructions}>
                    Click the button to scan the QR code generated by the SLS desktop application
                </Text>
                <View style={styles.qrcontainer}>
                    <QRCodeScanner
                        cameraStyle={styles.qrstyle}
                        showMarker={true}
                        markerStyle={{borderColor: colors.darkPurple}}
                        onRead={ (e) => (this.pairDevice(e.data))} />
                </View>
            </View>
        );
    }
}


const styles = StyleSheet.create({
    qrstyle: {
        height: 200,
        marginVertical: 40
    },
    qrcontainer: {
        height: 200,
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    }
});

export default PairingScreen;
