import React from "react";
import {Button, Dimensions, StyleSheet, Text, TouchableOpacity, View} from "react-native";
import {colors, Header, HorizontalSeparator, NavigationLink, TextField, commonStyles} from "./common";

const width = Dimensions.get('window').width; //full width
const height = Dimensions.get('window').height; //full height

class PairingScreen extends React.Component {
    render() {
        return (
            <View>
                <Header title='Pairing Device'/>
                <View style={{alignItems: "center"}}>
                    <Text  style={commonStyles.instructions}>
                        Click the button to scan the QR code generated by the SLS desktop application
                    </Text>
                    <TouchableOpacity
                        style={commonStyles.submitButton}>
                        <Text style={commonStyles.buttonText}>Scan QR code</Text>
                    </TouchableOpacity>
                </View>
            </View>
        );
    }
}

export default PairingScreen;